[package]
name = "linkshell"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "linkshell"
path = "src/main.rs"

[[bin]]
name = "linkshell-ctl"
path = "src/bin/ctl.rs"

[dependencies]
ratatui = "0.25"
crossterm = "0.27"
pty-process = { version = "0.4", features = ["async"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
anyhow = "1.0.102"
vt100 = "0.15"
arboard = "3"
reqwest = { version = "0.11", features = ["json"] }
toml = "0.8"
